### PR TITLE
changed README.md and Calculator.java

### PR DESCRIPTION
**Pull request by OldSharkDmi**
Merge branches with Pasha

### CODE REVIEW

**Review by AngryRaccoon77 — APPROVED** [review]
Approve

**Comment by OldSharkDmi** [comment]
okay

**Comment by OldSharkDmi** [comment]
i like this programm so much

**Review by AngryRaccoon77 — APPROVED** [review]

**Review by OldSharkDmi — COMMENTED** [review]
posmotrel

**Review by AngryRaccoon77 — APPROVED** [review]
OK

**Pull request closed without merging**
